function results = runExercise1(dateInfo, product, eni, axa, market, Nsim)
% RUNEXERCISE1 Executes the pricing logic and report generation for Exercise 1.
%
% INPUTS:
%   dateInfo: Struct containing refDate, matDate, day-count conventions
%   product : Struct containing principal, protection, alpha, weights, spread, paymentsPerYear
%   eni     : Struct containing spot, sigma, dividendYield
%   axa     : Struct containing spot, sigma, dividendYield
%   market  : Struct containing dates, discounts, zeroRates, rho
%   Nsim    : Number of Monte Carlo simulations
%
% OUTPUTS:
%   results : Struct containing final computed values (optional, for later use)


    % Payment dates
    [payDates, detailsDates] = computePaymentDates( ...
        dateInfo.refDate, ...
        dateInfo.matDate, ...
        product.paymentsPerYear, ...
        dateInfo.paymentAdjust);

    % Coupon via LogNormal approximation and discount factor
    [dfMat, coupon, detailsCoupon] = computeCoupon( ...
        product.alpha, ...
        dateInfo.refDate, ...
        dateInfo.matDate, ...
        market.dates, ...
        market.discounts, ...
        product.weights, ...
        product.protection, ...
        eni.dividendYield, ...
        axa.dividendYield, ...
        market.rho, ...
        eni.sigma, ...
        axa.sigma, ...
        product.principal);

    % Coupon via Monte Carlo simulation
    [couponMC, CallMC, MCError, detailsMC] = computeCouponMC( ...
        Nsim, ...
        product.alpha, ...
        dateInfo.refDate, ...
        dateInfo.matDate, ...
        dfMat, ...
        product.weights, ...
        product.protection, ...
        eni.dividendYield, ...
        axa.dividendYield, ...
        market.rho, ...
        eni.sigma, ...
        axa.sigma, ...
        product.principal);

    % Floater BPV
    bpvFloater = computeBpvFloater( ...
        payDates, ...
        market.dates, ...
        market.discounts, ...
        dateInfo.refDate);

    % X percentage via LogNormal approximation
    xPerc = 1 ...
        - dfMat ...
        + product.spread * bpvFloater ...
        + (1 - product.protection) * dfMat ...
        - coupon / product.principal;

    % X percentage via MC simulation
    xPercMC = 1 ...
        - dfMat ...
        + product.spread * bpvFloater ...
        + (1 - product.protection) * dfMat ...
        - couponMC / product.principal;

    % Report
    printExercise1Report( ...
        product.principal, ...
        dateInfo.refDate, ...
        dateInfo.matDate, ...
        product.protection, ...
        product.alpha, ...
        product.spread, ...
        market.rho, ...
        dfMat, ...
        bpvFloater, ...
        coupon, ...
        couponMC, ...
        xPerc, ...
        xPercMC, ...
        detailsDates, ...
        detailsCoupon, ...
        detailsMC);
        
    % Package key outputs into a struct in case you need them in the main script later
    results.xPerc = xPerc;
    results.coupon = coupon;
    results.couponMC = couponMC;
    results.bpvFloater = bpvFloater;

end