function results = runExercise2(underlying, dateInfo, product, marketData, market)
% RUNEXERCISE2 Executes the pricing logic, report, and plot for Exercise 2.
%
% INPUTS:
%   underlying : Struct containing underlying market data
%   dateInfo   : Struct containing refDate, matDate, day-count conventions
%   product    : Struct containing notional, digitalCoupon
%   marketData : Raw data loaded from 'eurostoxx_Poli.mat'
%   market     : Struct containing bootstrapped curve dates, discounts, zeroRates
%
% OUTPUTS:
%   results    : Struct containing final computed values
    
    % Product payoff
    product.digitalPayoff = product.notional * product.digitalCoupon;

    % Discount factor
    results.dfMat = getDiscountFactorByZeroRatesLinearInterp( ...
        dateInfo.refDate, dateInfo.matDate, market.dates, market.discounts);

    % Forward and ATM volatility
    results.forward = underlying.spot * exp(-underlying.dividendYield * dateInfo.timeToMaturity) / results.dfMat;
    results.strikeAtm = results.forward;
    results.sigmaAtm = interp1( ...
        underlying.strikes, underlying.volSmile, results.strikeAtm, 'spline');

    % Direct pricing
    results.priceBlack = priceDigitalBlack( ...
        results.forward, ...
        results.strikeAtm, ...
        results.sigmaAtm, ...
        dateInfo.timeToMaturity, ...
        results.dfMat, ...
        product.digitalPayoff);
        
    results.priceSmile = priceDigitalSmile( ...
        results.forward, ...
        results.strikeAtm, ...
        underlying.strikes, ...
        underlying.volSmile, ...
        dateInfo.timeToMaturity, ...
        results.dfMat, ...
        product.digitalPayoff);

    % Black price and smile correction (using your custom functions)
    [results.blackPrice, blackDetails] = computeBlackPrice( ...
        results.dfMat, marketData, dateInfo.refDate, dateInfo.matDate);
        
    [results.correctionTerm, correctionDetails] = computeCorrectionTerm( ...
        marketData, results.dfMat, dateInfo.refDate, dateInfo.matDate);
        
    results.correctedPrice = (results.blackPrice - results.correctionTerm);

    % Report
    printExercise2Report( ...
        product.notional, ...
        product.digitalPayoff, ...
        dateInfo.refDate, ...
        dateInfo.matDate, ...
        results.dfMat, ...
        results.blackPrice, ...
        results.correctionTerm, ...
        results.correctedPrice, ...
        blackDetails, ...
        correctionDetails);

    % Implied volatility smile plot
    plotImpliedVolatilitySmile( ...
        marketData, correctionDetails, results.dfMat, dateInfo.refDate, dateInfo.matDate);


end