function results = runExercise3(model3, fft3, dfMat, forward, Nsim)
% RUNEXERCISE3 Executes the pricing logic, diagnostics, and reports for Exercise 3.
%
% INPUTS:
%   model3  : Struct containing model parameters
%   fft3    : Struct containing FFT parameters
%   dfMat   : Discount factor to maturity
%   forward : ATM forward price
%   Nsim    : Number of Monte Carlo simulations
%
% OUTPUTS:
%   results : Struct containing final computed price vectors and diagnostics

    disp(' ')
    disp('============================================================')
    disp('Exercise 3')
    disp('============================================================')

    % CDF grid
    cdfGrid3.xMin = -20;
    cdfGrid3.xMax = 20;
    cdfGrid3.numPoints = fft3.N;

    % Fourier digital pricer
    digitalPricer3 = @(x) priceDigitalFFT( ...
        model3.charFunc, x, dfMat, fft3.M, fft3.xLeft, fft3.zLeft);

    % Digital diagnostics
    diag3 = runDigitalDiagnostics( ...
        digitalPricer3, ...
        model3.xVals, ...
        cdfGrid3.xMin, ...
        cdfGrid3.xMax, ...
        cdfGrid3.numPoints, ...
        '--- Digital prices via Fourier (pointwise grid) ---', ...
        'Exercise 3 - Digital prices on large grid', ...
        false, ...
        true);

    % Reconstruct CDF and simulate
    rng(100, 'twister'); 
    cdf3 = reconstructCdfFromDigital( ...
        digitalPricer3, ...
        forward, ...
        dfMat, ...
        cdfGrid3.xMin, ...
        cdfGrid3.xMax, ...
        cdfGrid3.numPoints, ...
        Nsim, ...
        '--- CDF diagnostics ---');

    % Final comparison
    disp(' ')
    disp('--- Final comparison ---')
    rng(101, 'twister');          
    [priceQuad3, priceFft3, priceMcDirect3, priceMcFromDigital3, priceRes, strikeVals3] = ...
        computePriceComparison( ...
            model3.xVals, ...
            model3.charFunc, ...
            dfMat, ...
            forward, ...
            fft3.M, ...
            fft3.xLeft, ...
            fft3.zLeft, ...
            Nsim, ...
            model3.pPlus, ...
            model3.pMinus, ...
            model3.mu, ...
            cdf3.terminalPrices);

    for idx = 1:length(model3.xVals)
        fprintf(['x = %+8.5f | K = %.8f | Quadrature = %.8f | FFT = %.8f | ', ...
                 'Direct MC = %.8f | MC from digital = %.8f | Residuals = %.8f\n'], ...
            model3.xVals(idx), ...
            strikeVals3(idx), ...
            priceQuad3(idx), ...
            priceFft3(idx), ...
            priceMcDirect3(idx), ...
            priceMcFromDigital3(idx), ...
            priceRes(idx));
    end

    % Report
    printPricingComparisonReport( ...
        model3.xVals, ...
        forward, ...
        priceQuad3, ...
        priceFft3, ...
        priceMcDirect3, ...
        priceMcFromDigital3, ...
        priceRes, ...
        diag3.digitalAtX, ...
        cdf3.cdfVals);

    % FFT parameter comparison
    fftComparison3 = compareFftParametersExercise3( ...
        model3.xVals, ...
        model3.charFunc, ...
        dfMat, ...
        forward, ...
        priceQuad3, ...
        fft3);

    % Plots
    plotDigitalAndCdfDiagnostics( ...
        diag3.xDiag, ...
        cdf3.digitalGrid, ...
        cdf3.yGrid, ...
        cdf3.cdfVals, ...
        cdf3.xSim, ...
        'Exercise 3');

    % Package results
    results.priceQuad = priceQuad3;
    results.priceFft = priceFft3;
    results.priceMcDirect = priceMcDirect3;
    results.priceMcFromDigital = priceMcFromDigital3;
    results.priceRes = priceRes;

    results.strikeVals = strikeVals3;
    results.digitalDiagnostics = diag3;
    results.cdfDiagnostics = cdf3;
    results.fftComparison = fftComparison3;

end