function resultsEx4 = runExercise4(model4, fft4, fftNts, dfMat, forward, Nsim)
% RUNEXERCISE4 Pricing and diagnostics for Exercise 4.
%
% INPUTS:
%   model4  : struct
%             Model parameters for the NIG/NTS setting.
%             Required fields:
%               sigma, kappa, eta, timeToMaturity, xVals
%
%   fft4    : struct
%             FFT parameters for the NIG case, alpha = 1/2.
%             Required fields:
%               M, xLeft, zLeft, xGrid
%
%   fftNts  : struct
%             FFT parameters for the NTS case, alpha = 1/3.
%             Required fields:
%               M, xLeft, zLeft
%
%   dfMat   : numeric scalar
%             Discount factor to maturity.
%
%   forward : numeric scalar
%             Forward price.
%
%   Nsim    : integer
%             Number of Monte Carlo simulations.
%
% OUTPUT:
%   resultsEx4 : struct
%                Contains NIG prices, NTS prices, FFT error diagnostics,
%                CDF diagnostics, and moment diagnostics.

    disp(' ')
    disp('============================================================')
    disp('Exercise 4')
    disp('============================================================')

    %% Common setup
    cdfGrid4.xMin = -3.0;
    cdfGrid4.xMax = 3.0;
    cdfGrid4.numPoints = 4001;

    xVals = model4.xVals(:).';

    % Print only representative points in pricing tables.
    idxPrint = unique([1, round(numel(xVals) / 2), numel(xVals)]);

    %% ============================================================
    %  NIG case, alpha = 1/2
    % =============================================================
    disp(' ')
    disp('--- NIG model, alpha = 1/2 ---')

    charExpNig = @(u) (model4.timeToMaturity / model4.kappa) .* ...
        (1 - sqrt(1 + model4.kappa * model4.sigma^2 .* ...
        (u.^2 + 1i * u .* (1 + 2 * model4.eta))));

    muNig = -real(charExpNig(-1i));
    charFuncNig = @(u) exp(charExpNig(u) + 1i * u * muNig);

    digitalPricerNig = @(x) priceDigitalFFT( ...
        charFuncNig, x, dfMat, fft4.M, fft4.xLeft, fft4.zLeft);

    % Digital diagnostics.
    % Last argument = false means: do not print pointwise digital prices.
    diag4 = runDigitalDiagnostics( ...
        digitalPricerNig, ...
        xVals, ...
        cdfGrid4.xMin, ...
        cdfGrid4.xMax, ...
        cdfGrid4.numPoints, ...
        '--- Digital diagnostics, NIG ---', ...
        'Exercise 4 - NIG digital prices on large grid', ...
        false, ...
        false);

    % CDF reconstruction and sampling
    rng(200, 'twister');          
    cdf4 = reconstructCdfFromDigital( ...
        digitalPricerNig, ...
        forward, ...
        dfMat, ...
        cdfGrid4.xMin, ...
        cdfGrid4.xMax, ...
        cdfGrid4.numPoints, ...
        Nsim, ...
        '--- CDF diagnostics, NIG ---');

    % NIG price comparison
    rng(201, 'twister');          
    [priceNigQuad, priceNigFft, priceNigMcFromDigital, priceNigMcDirect, strikeVals4] = ...
        computePriceComparisonNIG( ...
            xVals, ...
            dfMat, ...
            forward, ...
            model4.sigma, ...
            model4.kappa, ...
            model4.eta, ...
            model4.timeToMaturity, ...
            fft4.xGrid, ...
            Nsim, ...
            cdf4.terminalPrices, ...
            charFuncNig, ...
            muNig);

    printPricingTable( ...
        'NIG pricing comparison, selected points', ...
        xVals, ...
        strikeVals4, ...
        priceNigQuad, ...
        priceNigFft, ...
        priceNigMcDirect, ...
        priceNigMcFromDigital, ...
        idxPrint);

    errNig = computeErrors( ...
        priceNigQuad, ...
        priceNigFft, ...
        priceNigMcDirect, ...
        priceNigMcFromDigital);

    printErrorSummary('NIG error summary', errNig);

    %% NIG FFT sensitivity
    fftSensitivityNig = runFftSensitivity( ...
        'NIG FFT sensitivity', ...
        charFuncNig, ...
        xVals, ...
        dfMat, ...
        forward, ...
        priceNigQuad, ...
        fft4.M, ...
        [40, 60, 80]);

    %% NIG moment comparison
    hBase = 5e-3;
    hGrid = [1e-2, 5e-3, 1e-3, 1e-4];

    momentsComparisonNig = compareNigMoments(charFuncNig, hBase, hGrid);

    %% ============================================================
    %  NTS case, alpha = 1/3
    % =============================================================
    alphaNts = 1 / 3;

    charExpNts = @(u) (model4.timeToMaturity ./ model4.kappa) .* ...
        ((1 - alphaNts) / (model4.kappa * alphaNts)) .* ...
        (1 - (1 + (model4.kappa / (1 - alphaNts)) .* model4.sigma^2 .* ...
        (u.^2 + 1i * u .* (1 + 2 * model4.eta))).^alphaNts);

    muNts = -real(charExpNts(-1i));
    charFuncNts = @(u) exp(charExpNts(u) + 1i * u * muNts);

    priceNtsQuad = runPricingFourier(charFuncNts, xVals, dfMat, forward);

    priceNtsFft = runPricingFourier( ...
        charFuncNts, ...
        xVals, ...
        dfMat, ...
        forward, ...
        fftNts.M, ...
        fftNts.xLeft, ...
        fftNts.zLeft);

    strikeValsNts = forward .* exp(-xVals);

    % NTS table: only Quadrature and FFT are printed.
    printFourierPricingTable( ...
        'NTS alpha = 1/3 pricing comparison, selected points', ...
        xVals, ...
        strikeValsNts, ...
        priceNtsQuad, ...
        priceNtsFft, ...
        idxPrint);

    % Reuse the generic error function, with no MC prices for NTS.
    errNts = computeErrors( ...
        priceNtsQuad, ...
        priceNtsFft, ...
        NaN(size(priceNtsQuad)), ...
        NaN(size(priceNtsQuad)));

    printErrorSummary('NTS alpha = 1/3 error summary', errNts);

    %% NTS FFT sensitivity
    fftSensitivityNts = runFftSensitivity( ...
        'NTS alpha = 1/3 FFT sensitivity', ...
        charFuncNts, ...
        xVals, ...
        dfMat, ...
        forward, ...
        priceNtsQuad, ...
        fftNts.M, ...
        [40, 60, 80]);

    %% Plots
    plotDigitalAndCdfDiagnostics( ...
        diag4.xDiag, ...
        cdf4.digitalGrid, ...
        cdf4.yGrid, ...
        cdf4.cdfVals, ...
        cdf4.xSim, ...
        'Exercise 4 - NIG');

    %% Package results
    resultsEx4.priceNigQuad = priceNigQuad;
    resultsEx4.priceNigFft = priceNigFft;
    resultsEx4.priceNigMcFromDigital = priceNigMcFromDigital;
    resultsEx4.priceNigMcDirect = priceNigMcDirect;
    resultsEx4.errNig = errNig;
    resultsEx4.fftSensitivityNig = fftSensitivityNig;

    resultsEx4.priceNtsQuad = priceNtsQuad;
    resultsEx4.priceNtsFft = priceNtsFft;
    resultsEx4.errNts = errNts;
    resultsEx4.fftSensitivityNts = fftSensitivityNts;

    resultsEx4.momentsComparisonNig = momentsComparisonNig;

    resultsEx4.diagNig = diag4;
    resultsEx4.cdfNig = cdf4;

    resultsEx4.charFuncNig = charFuncNig;
    resultsEx4.muNig = muNig;
    resultsEx4.charFuncNts = charFuncNts;
    resultsEx4.muNts = muNts;

end